### ISSUE TITLE
Shallty Bot Discord Offline kurang lebih 2 mingguan

### ISSUE THREAD

**Issue by Akouji** [gegehprast/shallty#4]
Pak botnya gak diidupin lagi kah?

Gada rencana share script botnya pak biar bisa _self hosting_ 😂

**Comment by gegehprast** [comment]
> Pak botnya gak diidupin lagi kah?
> 
> Gada rencana share script botnya pak biar bisa _self hosting_ 😂

Botnya offline karena server parser-nya juga offline. Belum ada rencana mau share source code-nya, karena sebenernya dia juga cuma consume API ini. 

Kabar baik buat kamu, ini server parser-nya udah online lagi. Tapi bot-nya masih nunggu dulu ya. Sekarang lagi renovasi, sama lagi berusaha bikin ekstensi chrome-nya (masih nunggu review dari google).
